### PR TITLE
Added Sorting Algorithms.

### LINKED ISSUE #41: Add all the sorting algorithms in c++
I'll work on this

### PR DESCRIPTION
**Pull request by prabhat7k**
resolved #41

### CODE REVIEW

**Comment by gdscgndec** [comment]
Your code of Bucket sort, Count sort and Selection sort isn't working for negative integers. Kindly rectify it.

**Review by gdscgndec — CHANGES_REQUESTED** [review]
Some of algorithms aren't working for negative integers. Kindly rectify it.

**Comment by prabhat7k** [comment]
@gdscgndec those algorithms don't work for negative integers, hence are not used.

**Comment by gdscgndec** [comment]
Are you talking about Selection Sort ?

**Comment by prabhat7k** [comment]
@gdscgndec I've updated the selectionSort. Please review the commit.

**Review by gdscgndec — APPROVED** [review]
Great!

**Pull request merged**
